/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  ERC721AQueryablePolicies,
  ERC721AQueryablePoliciesInterface,
} from "../../../../contracts/TableLand/policies/ERC721AQueryablePolicies";

const _abi = [
  {
    inputs: [],
    name: "ERC721AQueryablePoliciesUnauthorized",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220286ffcfa8a4347db035393c17cb2d319346d56237df579556fcb1c3fb9164eaa64736f6c63430008140033";

type ERC721AQueryablePoliciesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC721AQueryablePoliciesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC721AQueryablePolicies__factory extends ContractFactory {
  constructor(...args: ERC721AQueryablePoliciesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ERC721AQueryablePolicies> {
    return super.deploy(overrides || {}) as Promise<ERC721AQueryablePolicies>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ERC721AQueryablePolicies {
    return super.attach(address) as ERC721AQueryablePolicies;
  }
  override connect(signer: Signer): ERC721AQueryablePolicies__factory {
    return super.connect(signer) as ERC721AQueryablePolicies__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC721AQueryablePoliciesInterface {
    return new utils.Interface(_abi) as ERC721AQueryablePoliciesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC721AQueryablePolicies {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC721AQueryablePolicies;
  }
}
