/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daiJoinSol from "./DaiJoin.sol";
export type { daiJoinSol };
import type * as savingsDaiSol from "./SavingsDai.sol";
export type { savingsDaiSol };
import type * as tableLand from "./TableLand";
export type { tableLand };
export type { CurrencyPrice } from "./CurrencyPrice";
export type { ILGuardTable } from "./ILGuardTable";
export type { ISavingsDai } from "./ISavingsDai";
export type { MonitorDAI } from "./MonitorDAI";
export type { Vat } from "./Vat";
