/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tableLand from "./TableLand";
export type { tableLand };
export type { CurrencyPrice } from "./CurrencyPrice";
export type { ILGuardTable } from "./ILGuardTable";
