[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
auto_detect_solc = true
optimizer_runs = 10
via_ir = true
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonMumbai = "https://rpc.ankr.com/polygon_mumbai"
gnosis = "https://rpc.gnosischain.com"
mantleTestnet = "https://rpc.testnet.mantle.xyz"
scrollSepolia = "https://rpc.ankr.com/scroll_sepolia_testnet"
gnosisChiado = "https://rpc.chiadochain.net"

[etherscan]
polygonMumbai = { key = "${ETHERSCAN_API_KEY}" }
scrollSepolia = { key = "${ETHERSCAN_API_KEY}" , url = "https://api-sepolia.scrollscan.dev/api" }